name: test
on: [push]
permissions:
  contents: write
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - name: generate test coverage
        run: go test ./... -coverprofile=./cover.out -covermode=atomic